project_name: bible
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy

builds:
  -
    id: darwin
    goarch:
      - amd64
      - arm64
    goos:
      - darwin

  -
    id: linux
    goarch:
      - arm64
      - amd64
      - arm
    goarm:
      - 5
    goos:
      - linux

  -
    id: windows
    goarch:
      - amd64
    goos:
      - windows

archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
    - database/bible.db

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/Jmainguy/bible
  description: A command line bible
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  release: 1
  replacements:
    amd64: x86_64
  overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{.Release}}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}-{{.Release}}_{{ .Arch }}"
  formats:
  - deb
  - rpm

brews:
  - tap:
      owner: jmainguy
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Jmainguy/bible
    description: "A command line bible"
    license: "GPL-2.0"
    commit_author:
      name: Jonathan Mainguy
      email: jon@soh.re
    test: |
      system "#{bin}/bible"
    install: |
      bin.install "bible"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
